name: XCS236_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cloudpickle=3.0.0
  - cycler=0.11.0
  - h5py=3.11.0
  - lockfile=0.12.2
  - opt-einsum=3.3.0
  - packaging=24.1
  - pandas=2.2.2
  - pickleshare=0.7.5
  - python-dateutil=2.9.0post0
  - requests=2.32.3
  - scipy=1.13.1
  - six=1.16.0
  - scikit-learn=1.4.2
  - tensorboard=2.17.0
  - pytest=7.4.4
  - imageio=2.33.1
  - svglib=1.5.1
  - googledrivedownloader=0.4
  - matplotlib=3.8.0
  - pyyaml=6.0.1
  - tqdm=4.66.4
  - regex=2024.7.24
  - thefuzz=0.22.1
  - rapidfuzz=3.5.2
  - seaborn=0.13.2
  - pip=24.0
  - pip:
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.4.0+cu118
    - "--find-links https://download.pytorch.org/whl/torchvision/"
    - torchvision==0.19.0+cu118
    - rouge-score==0.1.2
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - huggingface-hub==0.24.5
    - transformers==4.44.0
    - datasets==2.20.0
    - numpy==1.26.4
